services:
  postgres:
    image: postgres:16
    ports:
      - 54320:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - ws

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./api:/app
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "core.wsgi:application" ]
    depends_on:
      - postgres
      - rabbitmq

  ws:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8001:8001
    env_file:
      - .env
    volumes:
      - ./api:/app
    command: [ "daphne", "-b", "0.0.0.0", "-p", "8001", "core.asgi:application" ]
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: