# Generated by Django 5.1.1 on 2024-09-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_backtests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtest',
            old_name='trades',
            new_name='strategies',
        ),
    ]
