# Generated by Django 5.1.1 on 2024-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_backtests', '0002_rename_trades_backtest_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='period',
            field=models.CharField(default='d', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backtest',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
    ]
