# Generated by Django 5.1.1 on 2024-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_backtests', '0003_backtest_period_alter_backtest_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='period',
            field=models.CharField(choices=[('h', 'Hourly'), ('d', 'Daily'), ('w', 'Weekly')]),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='ticker',
            field=models.CharField(),
        ),
    ]
